src/kisRegBundle/Entity/Plik.php
<?php

namespace kisRegBundle\Entity;

use Doctrine\ORM\Mapping AS ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use kisRegBundle\Lib\Globals;

/**
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 */
class Plik
{
    /**
     * @ORM\PreUpdate()
     */
    public function beforeUpdate(){
      $this->uploadSupport();
    }
    /**
     * @ORM\PrePersist()
     */
    public function beforeCreate(){
      $this->uploadSupport();
      $this->inicjacja();
    }
    /**
     * @ORM\PostRemove()
     */
    public function afterRemove(){
        $this->removeUpload();
    }
    public function uploadSupport(){
        if ($this->getFile() == null) {
            return;
        }
        $val_getCacheName = $this->getCacheName();
        if(!empty($val_getCacheName)){
            @unlink($this->getLocalName());
        }

       $this->setMime($this->getFile()->getMimeType());
        $val_getNazwa = $this->getNazwa();
        if(empty($val_getNazwa))
          $this->setNazwa($this->getFile()->getClientOriginalName());
        $this->setCacheName(
            uniqid(
                md5(
                    $this->getNazwa()
                ).'-',
            true)
        );
        $this->getFile()->move(
            Globals::getFileStorageDir(),
            $this->getCacheName()
        );
        $this->setWielkosc(filesize($this->getLocalName()));
        $this->file = null;
    }
    private function removeUpload(){
        if (file_exists($this->getLocalName())) {
            @unlink($this->getLocalName());
        }
    }
    private function inicjacja(){
        $this->setUtworzenie(new \DateTime());
        if(!isset($this->kolejnosc))
            $this->setKolejnosc(1);
    }
    private function sprawdzeniePoprawnosci(){
      $plik = $this->getFile();
      if($plik === null)
        return false;
      if(! $plik->isValid())
        return false;
      return true;

    }
/******************************************************************************/
    /**
     * @ORM\Id
     * @ORM\Column(type="guid")
     * @ORM\GeneratedValue(strategy="UUID")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $utworzenie;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nazwa;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $wielkosc;

    /**
     * @ORM\Column(type="string", length=64, nullable=true)
     */
    private $mime;

    /**
     * @ORM\Column(type="string", unique=true, length=255, nullable=true)
     */
    private $cacheName;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $kolejnosc;

/******************************************************************************/
/** interfej obsługi plików                                                  **/
/******************************************************************************/
    private function getLocalName(){
      return Globals::getFileStorageDir().DIRECTORY_SEPARATOR.$this->getCacheName();
    }
    public function getData(){
      return file_get_contents($this->getLocalName());
    }
    /**
     * @Assert\File(maxSize="6000000")
     */
    private $file;
    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;
    }

    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }
    public function __toString(){
        return $this->getNazwa().'('.$this->getMime().')';
    }
	/**
	 * Alias for getData
	 */
	public function getContents(){
		return $this->getData();
	}

    /**
     * Get id
     *
     * @return guid
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set utworzenie
     *
     * @param \DateTime $utworzenie
     *
     * @return Plik
     */
    public function setUtworzenie($utworzenie)
    {
        $this->utworzenie = $utworzenie;

        return $this;
    }

    /**
     * Get utworzenie
     *
     * @return \DateTime
     */
    public function getUtworzenie()
    {
        return $this->utworzenie;
    }

    /**
     * Set nazwa
     *
     * @param string $nazwa
     *
     * @return Plik
     */
    public function setNazwa($nazwa)
    {
        $this->nazwa = $nazwa;

        return $this;
    }

    /**
     * Get nazwa
     *
     * @return string
     */
    public function getNazwa()
    {
        return $this->nazwa;
    }

    /**
     * Set wielkosc
     *
     * @param integer $wielkosc
     *
     * @return Plik
     */
    public function setWielkosc($wielkosc)
    {
        $this->wielkosc = $wielkosc;

        return $this;
    }

    /**
     * Get wielkosc
     *
     * @return integer
     */
    public function getWielkosc()
    {
        return $this->wielkosc;
    }

    /**
     * Set mime
     *
     * @param string $mime
     *
     * @return Plik
     */
    public function setMime($mime)
    {
        $this->mime = $mime;

        return $this;
    }

    /**
     * Get mime
     *
     * @return string
     */
    public function getMime()
    {
        return $this->mime;
    }

    /**
     * Set cacheName
     *
     * @param string $cacheName
     *
     * @return Plik
     */
    public function setCacheName($cacheName)
    {
        $this->cacheName = $cacheName;

        return $this;
    }

    /**
     * Get cacheName
     *
     * @return string
     */
    public function getCacheName()
    {
        return $this->cacheName;
    }

    /**
     * Set kolejnosc
     *
     * @param integer $kolejnosc
     *
     * @return Plik
     */
    public function setKolejnosc($kolejnosc)
    {
        $this->kolejnosc = $kolejnosc;

        return $this;
    }

    /**
     * Get kolejnosc
     *
     * @return integer
     */
    public function getKolejnosc()
    {
        return $this->kolejnosc;
    }
}

src/kisRegBundle/Entity/kisRegObject.php
<?php
namespace kisRegBundle\Entity;

interface kisRegObject {
    public function getThumb();
    public function __toString();
    public function getName();
    public function getDesc();
    public function getShortDesc();
    public function getLinked();
    public function getObjectType();
    public function getAbsoluteTime();
}

src/kisRegBundle/Form/GrupaType.php
<?php

namespace kisRegBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use EWZ\Bundle\RecaptchaBundle\Form\Type\EWZRecaptchaType;
use EWZ\Bundle\RecaptchaBundle\Validator\Constraints\IsTrue as RecaptchaTrue;
use kisRegBundle\Entity\Zajecia;
use kisRegBundle\Entity\Grupa;

class GrupaType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('opiekun')->add('email')->add('szkola')->add('telefon')->add('potwierdzono')->add('uwagi')
        ->add('zapisy',CollectionType::class,[
            'label'=>'Zajecia',
            'entry_type'   => RejestracjaZapisType::class
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'kisRegBundle\Entity\Grupa'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'kisregbundle_grupa';
    }


}

src/kisRegBundle/Form/PlikBezNazwyType.php
<?php

namespace kisRegBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use kisRegBundle\Form\PlikUploadFieldType;


class PlikBezNazwyType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('file',FileType::class,array('label'=>'Wybierz plik','multiple'=>false))
            ->add('kolejnosc')
        ;
    }
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(['data_class' => 'kisRegBundle\Entity\Plik']);
    }
    public function getBlockPrefix(){
        return 'kisRegBundle_plik_bez_nazwy';
    }
}

src/kisRegBundle/Form/PlikType.php
<?php

namespace kisRegBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use kisRegBundle\Form\PlikUploadFieldType;
use Symfony\Component\Form\Extension\Core\Type\FileType;


class PlikType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nazwa',null,array('label'=>'Nazwa pliku'))
            ->add('file',FileType::class,array('label'=>' '))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(['data_class' => 'kisRegBundle\Entity\Plik']);
    }
    public function getBlockPrefix(){
        return 'kisRegBundle_plik';
    }
}

src/kisRegBundle/Form/PytanieType.php
<?php

namespace kisRegBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PytanieType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('tresc')->add('odpowiedzA')->add('odpowiedzB')->add('odpowiedzC')->add('odpowiedzD')->add('poprawnaOdpowiedz')->add('kolejnosc')->add('aktywne');
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'kisRegBundle\Entity\Pytanie'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'kisregbundle_pytanie';
    }


}

src/kisRegBundle/Form/RejestracjaGrupaType.php
<?php

namespace kisRegBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use EWZ\Bundle\RecaptchaBundle\Form\Type\EWZRecaptchaType;
use EWZ\Bundle\RecaptchaBundle\Validator\Constraints\IsTrue as RecaptchaTrue;
use kisRegBundle\Entity\Zajecia;
use kisRegBundle\Entity\Grupa;

class RejestracjaGrupaType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('opiekun',null,array('label'=>'Opiekun','attr'=>['placeholder'=>'Imię i nazwisko...']))
        ->add('email',EmailType::class,array('label'=>'E-Mail','attr'=>['placeholder'=>'Email...']))
        ->add('szkola',null,array('label'=>'Szkoła','attr'=>['placeholder'=>'Nazwa szkoły lub instytucji...']))
        ->add('telefon',null,array('label'=>'Telefon','attr'=>['placeholder'=>'Numer telefonu...']))
        ->add('zapisy',CollectionType::class,[
            'label'=>'Zajecia',
            'entry_type'   => RejestracjaZapisType::class
        ])
        ->add('recaptcha', EWZRecaptchaType::class,array(
            'mapped'      => false,
            'constraints' => array(
                    new RecaptchaTrue()
                    )
                )
            )
        ->add('send', SubmitType::class,array('label'=>'Wyślij' ));
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'kisRegBundle\Entity\Grupa'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'kisregbundle_rejestracjagrupa';
    }


}

src/kisRegBundle/Form/RejestracjaZapisType.php
<?php

namespace kisRegBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RejestracjaZapisType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('ilosc');
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'kisRegBundle\Entity\Zapis'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'kisregbundle_rejestracjazapis';
    }


}

src/kisRegBundle/Form/SkrotType.php
<?php

namespace kisRegBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class SkrotType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nazwa',TextType::class,['attr'=>['class'=>'form-control input-inline']])
            ->add('cel',TextType::class,['attr'=>['class'=>'form-control input-inline']])
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'kisRegBundle\Entity\Skrot'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'kisRegBundle_skrot';
    }


}

src/kisRegBundle/Form/StronaType.php
<?php

namespace kisRegBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class StronaType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nazwa',TextType::class,['attr'=>['class'=>'form-control input-inline']])
            ->add('tresc',
                TextareaType::class,
                [
                    'attr' => [
                        'class' => 'tinymce',
                        'height' => '600px'
                    ]
                ]
            )
            // ->add('tresc',TextType::class,['attr'=>['class'=>'form-control input-inline']])
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'kisRegBundle\Entity\Strona'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'kisRegBundle_strona';
    }


}

src/kisRegBundle/Form/UzytkownikNowyType.php
<?php

namespace kisRegBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;


class UzytkownikNowyType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username',null,['label'=>'Nazwa','required' => true,'attr'=>['class' => 'form-control input-inline password-field']])
            ->add('email',EmailType::class,['label'=>'EMail','required' => true,'attr'=>['class' => 'form-control input-inline password-field']])
            ->add('password', RepeatedType::class, [
                'type' => PasswordType::class,
                'invalid_message' => 'Hasła muszą się zgadzać',
                'options' => array('attr' => array('class' => 'form-control input-inline password-field')),
                'required' => true,
                'first_options'  => array('label' => 'Hasło'),
                'second_options' => array('label' => 'Powtórz hasło'),
            ])
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'kisRegBundle\Entity\Uzytkownik'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'kisRegBundle_uzytkownik_nowy';
    }


}

src/kisRegBundle/Resources/views/Form/Encje.html.twig
{% block choice_row -%}
    {% set force_error = true %}
    <fieldset class="ui-corner-all {% if (not compound or force_error|default(false)) and not valid %}error{% endif %}">
        <legend style="width:auto; margin-bottom: auto;">{{ form_label(form) }}</legend>
        {{ form_errors(form) }}
        {{ form_widget(form) }}
    </fieldset>
{%- endblock choice_row %}
{##############################################################################}
{% block entity_widget -%}
    {% if multiple -%}
        {% if errors|length > 0 -%}
            {% set attr = attr|merge({class: (attr.class|default('') ~ ' error')|trim}) %}
        {% endif %}
        <div style="display: none;">
            {% set options = preferred_choices %}
            {{- block('fancy_choice_widget_cbxhelper_options') -}}
            {% set options = choices %}
            {{- block('fancy_choice_widget_cbxhelper_options') -}}
        </div>
        <div class="row">
            <div class="col-xs-12 col-md-6 entity-not-selected">
                <fieldset style="max-height: 400px; overflow: auto;" class="ui-corner-all elements-contanier">
                    <legend style="margin-bottom: auto;">
                        <input onkeyup="{{id}}_search_update(this);" onkeydown="{{id}}_search_update(this);" onkeypress="{{id}}_search_update(this);" onchange="{{id}}_search_update(this);" onblur="{{id}}_search_update(this);" type="text" class="form-control input-inline" placeholder="Wpisz, aby wyszukać..." />
                    </legend>
                    {% set show_selected = false %}
                    {% set options = preferred_choices %}
                    {{- block('fancy_choice_widget_options') -}}
                    {% set options = choices %}
                    {{- block('fancy_choice_widget_options') -}}
                </fieldset>
                <div style="clear: both;"></div>
            </div>
            <div class="col-xs-12 col-md-6 entity-selected">
                <fieldset style="max-height: 400px; overflow: auto;" class="ui-corner-all elements-contanier">
                    <legend style="width:auto; margin-bottom: auto;">Wybrane</legend>
                    {% set show_selected = true %}
                    {% set options = preferred_choices %}
                    {{- block('fancy_choice_widget_options') -}}
                    {% set options = choices %}
                    {{- block('fancy_choice_widget_options') -}}
                </fieldset>
                <div style="clear: both;"></div>
            </div>
        </div>
        <script>
            function {{id}}_search_update(elem){
                var e = $(elem);
                var value = elem.value;
                var ec = e.parent().parent().find('.element-contanier');
                ec.hide();
                if(value.length > 1)
                    ec.filter(function(){
                        return $(this).text().toLocaleLowerCase().indexOf(value) != -1;
                    }).show();
            }
            function {{id}}_choice_click(elem){
                var e = $(elem);
                var r = e.parent().parent();
                var stateNow = r.hasClass('entity-not-selected');
                var value = e.attr('value');
                $('input.{{ id }}_cbx_helper').filter(function(){
                    return value == $(this).attr('value');
                }).prop("checked",stateNow);
                r.
                    parent().
                    find( ((stateNow)?'.entity-selected':'.entity-not-selected') ).
                    find('.elements-contanier').
                    append(e);
            }
        </script>
    {% else %}
        {{- block('choice_widget_collapsed') -}}
    {% endif %}
{%- endblock entity_widget %}
{##############################################################################}
{%- block fancy_choice_widget_cbxhelper_options -%}
    {% for group_label, choice in options %}
        {%- if choice is iterable -%}
            {% set options = choice %}
            {{- block('fancy_choice_widget_cbxhelper_options') -}}
        {%- else -%}
            <input class="{{ id }}_cbx_helper" type="checkbox" value="{{ choice.value }}" name="{{ full_name }}" {% if choice is selectedchoice(value) %} checked="checked"{% endif %} />
        {%- endif -%}
    {% endfor %}
{%- endblock fancy_choice_widget_cbxhelper_options -%}
{##############################################################################}
{%- block fancy_choice_widget_options -%}
    {% for group_label, choice in options %}
        {%- if choice is iterable -%}
            {% set options = choice %}
            {{- block('fancy_choice_widget_options') -}}
        {%- else -%}
            {% if choice is selectedchoice(value)==show_selected %}
                {% if attribute(choice.data,'getThumb') is defined %}
                    <span onclick="{{id}}_choice_click(this)"
                    class="element-contanier" style="{% if not show_selected %}display: none;{% endif %}"
                    value="{{ choice.value }}">
                        <div style="
                            cursor: pointer;
                            text-align:center;
                            margin: 7px;
                            width: 64px;
                            height: 128px;
                            float: left;
                            "{% if choice.attr %} {% set attr = choice.attr %}{{ block('attributes') }}{% endif %}>
                            <div class="ui-corner-all" style="
                                margin:0px;
                                padding: 0px;
                                width: 64px;
                                height: 64px;
                                background-image:url('{{choice.data.thumb|thumbUrl(64)}}');
                                background-repeat: no-repeat;
                                background-position: center center;
                                background-color: rgba(0,0,0,0.05);
                            " /></div>
                            <div>{{ choice_translation_domain is same as(false) ? choice.label : choice.label|trans({}, choice_translation_domain) }}</div>
                        </div>
                    </span>
                {% else %}
                    <span class="element-contanier" style="{% if not show_selected %}display: none;{% endif %}" onclick="{{id}}_choice_click(this)" value="{{ choice.value }}">
                        <div style="width: 100%;margin-top:2px;" class="btn btn-primary"{% if choice.attr %}{% set attr = choice.attr %}{{ block('attributes') }}{% endif %}>
                            {{ choice_translation_domain is same as(false) ? choice.label : choice.label|trans({}, choice_translation_domain) }}
                        </div>
                    </span>
                {% endif %}
            {% endif %}
        {%- endif -%}
    {% endfor %}
{%- endblock fancy_choice_widget_options -%}

src/kisRegBundle/Resources/views/Form/Rejestracja.html.twig
{% block choice_row -%}
    {% set force_error = true %}
    <fieldset class="ui-corner-all {% if (not compound or force_error|default(false)) and not valid %}error{% endif %}">
        <legend style="width:auto; margin-bottom: auto;">{{ form_label(form) }}</legend>
        {{ form_errors(form) }}
        {{ form_widget(form) }}
    </fieldset>
{%- endblock choice_row %}
{##############################################################################}
{% block _kisregbundle_rejestracjagrupa_zapisy_widget -%}
    {% if multiple -%}
        {% if errors|length > 0 -%}
            {% set attr = attr|merge({class: (attr.class|default('') ~ ' error')|trim}) %}
        {% endif %}

            {{- block('choice_widget_collapsed') -}}
    {% else %}
        {{- block('choice_widget_collapsed') -}}
    {% endif %}
{%- endblock _kisregbundle_rejestracjagrupa_zapisy_widget %}
{##############################################################################}
{%- block fancy_choice_widget_cbxhelper_options -%}
    {% for group_label, choice in options %}
        {%- if choice is iterable -%}
            {% set options = choice %}
            {{- block('fancy_choice_widget_cbxhelper_options') -}}
        {%- else -%}
            <input class="{{ id }}_cbx_helper" type="checkbox" value="{{ choice.value }}" name="{{ full_name }}" {% if choice is selectedchoice(value) %} checked="checked"{% endif %} />
        {%- endif -%}
    {% endfor %}
{%- endblock fancy_choice_widget_cbxhelper_options -%}
{##############################################################################}
{%- block fancy_choice_widget_options -%}
    {% for group_label, choice in options %}
        {%- if choice is iterable -%}
            {% set options = choice %}
            {{- block('fancy_choice_widget_options') -}}
        {%- else -%}
            {% if choice is selectedchoice(value)==show_selected %}
                {% if attribute(choice.data,'getThumb') is defined %}
                    <span onclick="{{id}}_choice_click(this)"
                    class="element-contanier" style="{% if not show_selected %}display: none;{% endif %}"
                    value="{{ choice.value }}">
                        <div style="
                            cursor: pointer;
                            text-align:center;
                            margin: 7px;
                            width: 64px;
                            height: 128px;
                            float: left;
                            "{% if choice.attr %} {% set attr = choice.attr %}{{ block('attributes') }}{% endif %}>
                            <div class="ui-corner-all" style="
                                margin:0px;
                                padding: 0px;
                                width: 64px;
                                height: 64px;
                                background-image:url('{{choice.data.thumb|thumbUrl(64)}}');
                                background-repeat: no-repeat;
                                background-position: center center;
                                background-color: rgba(0,0,0,0.05);
                            " /></div>
                            <div>{{ choice_translation_domain is same as(false) ? choice.label : choice.label|trans({}, choice_translation_domain) }}</div>
                        </div>
                    </span>
                {% else %}
                    <span class="element-contanier" style="{% if not show_selected %}display: none;{% endif %}" onclick="{{id}}_choice_click(this)" value="{{ choice.value }}">
                        <div style="width: 100%;margin-top:2px;" class="btn btn-primary"{% if choice.attr %}{% set attr = choice.attr %}{{ block('attributes') }}{% endif %}>
                            {{ choice_translation_domain is same as(false) ? choice.label : choice.label|trans({}, choice_translation_domain) }}
                        </div>
                    </span>
                {% endif %}
            {% endif %}
        {%- endif -%}
    {% endfor %}
{%- endblock fancy_choice_widget_options -%}