src/kisRegBundle/Entity/kisRegObject.php
<?php
namespace kisRegBundle\Entity;

interface kisRegObject {
    public function getThumb();
    public function __toString();
    public function getName();
    public function getDesc();
    public function getShortDesc();
    public function getLinked();
    public function getObjectType();
    public function getAbsoluteTime();
}

src/kisRegBundle/Resources/views/Admin/Common/delete_form.html.twig
<div style="display:none;">{{ form_start(form) }}{{ form_end(form) }}</div>
<a class="btn btn-danger" onclick="$(this).prev().find('form').submit()"><i class="fa fa-remove" aria-hidden="true"></i></a>

src/kisRegBundle/Resources/views/Admin/Common/elements_index.html.twig
<div>
    <h1 style="float: left;">{{title}}</h1>
    <a  style="float: right;" class="btn btn-success" href="{{ path(newPathName) }}">Dodaj nowe</a>
    <hr style="clear: both;" />
</div>
{% for element in elements %}
    <a style="
        text-align:center;
        margin: 7px;
        width: 64px;
        height: 128px;
        float: left;
        display: inline-block;" href="{{ path(editPathName, { 'id': element.id }) }}">
        <div class="ui-corner-all" style="
            margin:0px;
            padding: 0px;
            width: 64px;
            height: 64px;
            background-image:url('{{element.thumb|thumbUrl(64)}}');
            background-repeat: no-repeat;
            background-position: center center;
            background-color: rgba(0,0,0,0.05);
        " /></div>
        <div>{{ element.name }}</div>
    </a>
{% endfor %}
<hr style="clear: both;" />

src/kisRegBundle/Resources/views/Admin/Common/obsluga_uploadu_plikow.html.twig
<script type="text/javascript">
    $().ready(function(){
        $('#{{button_id}}').click(function(event) {
            event.preventDefault();
            var iloscPlikow = parseInt($(this).attr('plikicount'));
            if(isNaN(iloscPlikow)) iloscPlikow = 1*1;

            var nowy = $('#{{contanier}}').attr('data-prototype').replace(/__name__/g, iloscPlikow);
            nowy = $('<div></div>').append(nowy);
            nowy.attr('id','idplikuDoUploadowania_{{button_id}}_'+iloscPlikow);
            nowy.find('.panel-body').css('background','rgb(176, 245, 140)');
            iloscPlikow++;
            $(this).attr('plikicount',iloscPlikow);

            nowy.find('input').trigger('click').change(function(){
                $('#{{contanier}}').append(nowy);
            });
        });
    });
</script>